name: milibase
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0-296.4.beta

dependencies:
  flutter:
    sdk: flutter

  fluent_ui: ^4.15.1
  gap: ^3.0.1
  google_fonts: ^8.0.2
  intl: ^0.20.2
  sqflite_common_ffi: ^2.4.0+3
  path_provider: ^2.1.5
  drift: ^2.32.1
  drift_flutter: ^0.3.0
  uuid: ^4.5.3
  bitsdojo_window: ^0.1.6
  flutter_svg: ^2.2.4
  open_folder: ^0.0.3
  url_launcher: ^6.3.2
  super_bullet_list: ^0.0.3
  path: ^1.9.1
  http: ^1.6.0
  rxdart: ^0.28.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.32.1
  build_runner: ^2.14.0
flutter:
  uses-material-design: true
  assets:
    - assets/

